### ISSUE TITLE
Newtypes for arrays

### ISSUE THREAD

**Issue by EngosSoftware** [fudini/bendec#27]
I looks like using newtypes for arrays does not properly generate Rust code.
For example, configuring options like this:
`options: {
    meta: {
      'MyName': {newtype: {kind: NewtypeKind.Public}}
   }
}`
generates:
`pub type MyName = [AnsiChar; 8];`
instead of:
`pub struct MyName(pub [AnsiChar; 8]);`

Not sure if this is just wrong configuration.

**Comment by fudini** [comment]
v0.17.0 will let you upgrade array into a newtype
